### ISSUE TITLE
Feature 1: List Products ( REST API )

### ISSUE THREAD

**Issue by kv-b1-2022** [spriyam1221/supermarketApp-API#1]
#### User Story
* As a user, I should be able to view the products.

**Comment by spriyam1221** [comment]
What are the details to be displayed?

**Comment by kv-b1-2022** [comment]
Hi Priya,

We need to display the below product details:

- name
- price
- image 
- measurement

**Comment by spriyam1221** [comment]
I started working on this task.

**Comment by kv-b1-2022** [comment]
Priya,
Can you please, let us know when the task will get completed ?

**Comment by spriyam1221** [comment]
I need time 2-3 hours to complete.

**Comment by spriyam1221** [comment]
I have completed this task.

**Comment by kv-b1-2022** [comment]
#### Test Case 1: List products
* It is working.
